#!/bin/bash

cd "/usr/lib/southwest-bot/"
case "$1" in 
    scan)
        python southwest.py
        ;;
    update)
        python southwest.py "$2"
        ;;
    listen)
        python southwestMessenger.py
        ;;
    checkin)
        shift
        python southwest.py "$1" "$2" "$3" "$4" # confirmationNumber,firstName, lastName,id
        ;;
    send-message)
        shift
        python southwestMessenger.py $@
        ;;
esac
