#!/bin/bash

cd "/usr/lib/southwest-bot/"
mkdir "~/Southwest"
case "$1" in 
    scan)
        python southwest.py
        ;;
    check)
        python southwest.py "check"
        ;;
    update)
        python southwest.py "update"
        ;;
    listen)
        python southwestMessenger.py
        ;;
    checkin)
        shift
        python southwest.py "$1" "$2" "$3" "$4" # confirmationNumber,firstName, lastName,chatId
        ;;
    send-message)
        shift
        id="$1"
        shift
        python southwestMessenger.py "$id" "$@"
        ;;
esac
