#!/bin/bash

cd "/usr/lib/southwest-bot/"
case $1 in 
    scan)
        python southwest.py
        ;;
    listen)
        python southwestMessenger.py
        ;;
    checkin)
        shift
        python southwest.py $@
        ;;
    send-message)
        python southwestMessenger.py $@
        ;;
esac
